branches:
 only:
  - deploy

sudo: required
dist: trusty
addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable
language: node_js
node_js:
 - "9"

before_script:
  travis_wait 30
 # For using headless chrome with travis
 - export CHROME_BIN=chromium-browser
 - export DISPLAY=:99.0
 - sh -e /etc/init.d/xvfb start
 ####
 - sudo apt-get install lftp
 #- npm install
 - npm install -g bower
 # - npm install -g grunt-cli
 - bower install

script:
 # - grunt test # run karma and jamine testing
 - bash deploy.sh

notifications:
 email: false
