branches:
 only:
  - deploy

sudo: required
dist: trusty
addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable
language: node_js
node_js:
 - "6"

before_script:
 # For using headless chrome with travis
 - export CHROME_BIN=chromium-browser
 - export DISPLAY=:99.0
 - sh -e /etc/init.d/xvfb start
 ####
 - sudo apt-get install lftp

instal:
 - npm install -g bower
 - npm install -g grunt-cli
 - npm install
 - bower install

script:
 # - grunt test # run karma and jamine testing
 - lftp -f "
 - open $host
 - user $user $password
 - lcd .
 - bye
 - " 

notifications:
 email: false
