language: node_js
node_js:
 - "4.0"

before_script:
 - export CHROME_BIN=chromium-browser
 - export DISPLAY=:99.0
 - sh -e /etc/init.d/xvfb start
 - npm install -g bower
 - npm install -g grunt-cli
 - npm install
 - bower install

script:
 grunt test # run karma and jamine testing
